Adds DoD Advana repositories
Code-dot-mil/code.mil pull request #272
Opened 2021-04-22 17:31 UTC by vctrstrm

## Checklist

I have…

- [X] run the application locally (`./scripts/serve`) and verified that my changes behave as expected.
- [X] run the build process locally (`./scripts/build`) and make sure it builds correctly.
- [X] run the test suite (`./scripts/test`) and verified that all tests pass.
- [X] summarized below my changes and noted which issues (if any) this pull request fixes or addresses.
- [ ] thoroughly outlined below the steps necessary to test my changes.
- [ ] attached screenshots illustrating relevant behavior before and after my changes.
- [ ] read, understand, and agree to the terms described in [CONTRIBUTING.md](../CONTRIBUTING.md).
- [ ] added my name, email address, and copyright date to [CONTRIBUTORS.md](../CONTRIBUTORS.md).

## Summary of Changes

This pull request…

- Adds release JSON for gamechanger repos dod-advana org

## Testing

- N/A

## Screenshots

- N/A

2021-04-23 16:30 UTC, david-saeger requested changes

2021-04-23 16:30 UTC, david-saeger commented on src/_releases/github.com/dod-advana/gamechanger.json
> +    "repositoryURL": "https://github.com/dod-advana/gamechanger",
should this point to gamechanger-data instead? That seems to be where the work is.

2021-04-23 17:25 UTC, david-saeger commented on src/_releases/github.com/dod-advana/gamechanger.json
> +    "laborHours": 0,
@vctrstrm curious what you think the viability of getting an estimate laborHours might be. Doesn't need to be exact but these numbers do help GSA and others understand some context on the governments overall contributions to OSS. gsa provides some instruction on how to estimate this based on lines of code here https://github.com/GSA/code-gov/blob/master/docs/labor_hour_calc.md

2021-04-23 17:25 UTC, david-saeger commented on src/_releases/github.com/dod-advana/gamechanger.json
> +            "URL": "https://github.com/dod-advana/gamechanger/blob/main/LICENSE.md"
should this be pointing to the repo for gamechanger-data ?

2021-04-23 17:27 UTC, david-saeger commented on src/_releases/github.com/dod-advana/gamechanger.json
> +    "repositoryURL": "https://github.com/dod-advana/gamechanger",
should this be pointing to the gamechanger-data repo?

2021-04-23 17:27 UTC, david-saeger commented on src/_releases/github.com/dod-advana/gamechanger.json
> +      "URL": "https://github.com/dod-advana/gamechanger"
It might make sense to leave this as it seems to be serving as the landing page for the overall project.

2021-04-24 03:53 UTC, vctrstrm commented on src/_releases/github.com/dod-advana/gamechanger.json
> +    "laborHours": 0,
I'll check with product owners. One thing to note is that this project is going through a lot of development current with no particular end in sight, so whatever figure this might be - it'll need to be revised at some regular interval to stay close to reality.

2021-04-24 03:55 UTC, vctrstrm commented on src/_releases/github.com/dod-advana/gamechanger.json
> +    "repositoryURL": "https://github.com/dod-advana/gamechanger",
This is itself a repo, but yes - we do have the gamechanger-data and probably more repos in future. I'll add per-repo release files :+1:

2021-04-24 03:55 UTC, vctrstrm commented on src/_releases/github.com/dod-advana/gamechanger.json
> +            "URL": "https://github.com/dod-advana/gamechanger/blob/main/LICENSE.md"
i'll add per-repo release files

2021-04-24 03:55 UTC, vctrstrm commented on src/_releases/github.com/dod-advana/gamechanger.json
> +    "repositoryURL": "https://github.com/dod-advana/gamechanger",
i'll add per-repo release files

2021-04-26 13:39 UTC, david-saeger commented on src/_releases/github.com/dod-advana/gamechanger.json
> +    "laborHours": 0,
This release object is supposed to represent a particular release of this software so - if provided - the laborHours key would reflect continued effort in the next release.

2021-04-27 22:31 UTC, vctrstrm commented on src/_releases/github.com/dod-advana/gamechanger.json
> +    "laborHours": 0,
Just updated. We'll probably return to revise the number sometime down the line thought. Since we'll have multiple repositories and shared team - they will be set at 0 labor hours and all hours will be instead totaled in the entry for gamechanger meta repository. @david-saeger

2021-04-28 14:21 UTC, merged